development:
  adapter: postgresql
  encoding: unicode
  database: bazaar
  pool: 5
  username: alex
  password:

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encoding: unicode
  database: bazaar
  pool: 5
  username: bazaar
  password:
